/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
import java.util.Date;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.text.SimpleDateFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cnlightsoul
 */
public class FDAIndex extends javax.swing.JFrame {
    static String username = "default user";
    static ArrayList<Flight> flightInfo = new ArrayList();
    static ArrayList<Flight> searchedFlights = new ArrayList();
    static DefaultListModel<String> model = new DefaultListModel();
    static Customer currentCustomer;
    static String editingFlight = "";
    static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    static Trip editingTrip = null;
    static DefaultListModel<String> serviceModel = new DefaultListModel();
    static DefaultListModel<String> futureModel = new DefaultListModel();
    /**
     * Creates new form FDAIndex
     * @param uName
     */
    public FDAIndex(String uName) {
        username = uName;
        initComponents();
    }
    
    public FDAIndex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmBookingDialog = new javax.swing.JDialog();
        confirmTitleLabel = new javax.swing.JLabel();
        dialogInformation1 = new javax.swing.JLabel();
        proceedButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        dialogInformation2 = new javax.swing.JLabel();
        dialogInformation3 = new javax.swing.JLabel();
        dialogInformation4 = new javax.swing.JLabel();
        chooseSeatDialog = new javax.swing.JDialog();
        chooseSeatLabel = new javax.swing.JLabel();
        rowLabel = new javax.swing.JLabel();
        rowLabel1 = new javax.swing.JLabel();
        rowBox = new javax.swing.JComboBox<>();
        numberBox = new javax.swing.JComboBox<>();
        seatConfirmButton = new javax.swing.JButton();
        bookingSuccess = new javax.swing.JDialog();
        successLabel = new javax.swing.JLabel();
        successTextLabel = new javax.swing.JLabel();
        bkSuccessBackButton = new javax.swing.JButton();
        manageBookingFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        completedList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ongoingList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        futureList = new javax.swing.JList<>();
        competedLabel = new javax.swing.JLabel();
        futureLabel = new javax.swing.JLabel();
        ongoingLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        closeManageBookingButton = new javax.swing.JButton();
        editNcustomiseFrame = new javax.swing.JFrame();
        editLabel = new javax.swing.JLabel();
        editInfoLabel = new javax.swing.JLabel();
        se01Box = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        se02Box = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        boughtServicesList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        buyServiceButton = new javax.swing.JButton();
        changeSeatButton = new javax.swing.JButton();
        closePageButton = new javax.swing.JButton();
        cancelBookingButton = new javax.swing.JButton();
        removeServiceButton = new javax.swing.JButton();
        changeSeatDialog = new javax.swing.JDialog();
        changeSeatLabel = new javax.swing.JLabel();
        changeSeatRowLabel = new javax.swing.JLabel();
        changeSeatNumberLabel = new javax.swing.JLabel();
        changeSeatRowBox = new javax.swing.JComboBox<>();
        changeSeatNumberBox = new javax.swing.JComboBox<>();
        changeSeatConfirmButton = new javax.swing.JButton();
        cancelBookingDialog = new javax.swing.JDialog();
        warningCanceLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirmCancelButton = new javax.swing.JButton();
        notCancel = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        departureBox = new javax.swing.JComboBox<>();
        destinationBox = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        departureLabel = new javax.swing.JLabel();
        destinationLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        searchFlightButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foundFlightsList = new javax.swing.JList<>();
        bookFlightButton = new javax.swing.JButton();
        manageBookingButton = new javax.swing.JButton();

        confirmTitleLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        confirmTitleLabel.setText("Confirm Booking:");

        dialogInformation1.setText("Flight Information");
        dialogInformation1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        dialogInformation2.setText("Flight Information");
        dialogInformation2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        dialogInformation3.setText("Flight Information");
        dialogInformation3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        dialogInformation4.setText("Flight Information");
        dialogInformation4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout confirmBookingDialogLayout = new javax.swing.GroupLayout(confirmBookingDialog.getContentPane());
        confirmBookingDialog.getContentPane().setLayout(confirmBookingDialogLayout);
        confirmBookingDialogLayout.setHorizontalGroup(
            confirmBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmBookingDialogLayout.createSequentialGroup()
                .addGroup(confirmBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmBookingDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(confirmTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(confirmBookingDialogLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(confirmBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(confirmBookingDialogLayout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proceedButton))
                            .addGroup(confirmBookingDialogLayout.createSequentialGroup()
                                .addGroup(confirmBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dialogInformation1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dialogInformation2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dialogInformation3, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dialogInformation4, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 20, Short.MAX_VALUE)))))
                .addGap(55, 55, 55))
        );
        confirmBookingDialogLayout.setVerticalGroup(
            confirmBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmBookingDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialogInformation1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialogInformation2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialogInformation3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialogInformation4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(confirmBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(proceedButton))
                .addGap(32, 32, 32))
        );

        chooseSeatLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        chooseSeatLabel.setText("Please chooose your seat: ");

        rowLabel.setText("Row:");

        rowLabel1.setText("Number:");

        rowBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "D", "F" }));

        numberBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        seatConfirmButton.setText("Confirm");
        seatConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseSeatDialogLayout = new javax.swing.GroupLayout(chooseSeatDialog.getContentPane());
        chooseSeatDialog.getContentPane().setLayout(chooseSeatDialogLayout);
        chooseSeatDialogLayout.setHorizontalGroup(
            chooseSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseSeatDialogLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(chooseSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rowLabel)
                    .addComponent(rowBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(chooseSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rowLabel1)
                    .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
            .addGroup(chooseSeatDialogLayout.createSequentialGroup()
                .addGroup(chooseSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chooseSeatDialogLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(chooseSeatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chooseSeatDialogLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(seatConfirmButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chooseSeatDialogLayout.setVerticalGroup(
            chooseSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseSeatDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(chooseSeatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(chooseSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rowLabel)
                    .addComponent(rowLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chooseSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rowBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(seatConfirmButton)
                .addGap(47, 47, 47))
        );

        successLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        successLabel.setText("Congratulations !");

        successTextLabel.setText("Your flight booking is successful.");

        bkSuccessBackButton.setText("Back to Homepage");
        bkSuccessBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkSuccessBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookingSuccessLayout = new javax.swing.GroupLayout(bookingSuccess.getContentPane());
        bookingSuccess.getContentPane().setLayout(bookingSuccessLayout);
        bookingSuccessLayout.setHorizontalGroup(
            bookingSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingSuccessLayout.createSequentialGroup()
                .addGroup(bookingSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingSuccessLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(bookingSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(successTextLabel)
                            .addComponent(successLabel)))
                    .addGroup(bookingSuccessLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(bkSuccessBackButton)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        bookingSuccessLayout.setVerticalGroup(
            bookingSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingSuccessLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(successTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(bkSuccessBackButton)
                .addGap(26, 26, 26))
        );

        manageBookingFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                manageBookingFrameWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("My Bookings");

        jScrollPane2.setViewportView(completedList);

        jScrollPane3.setViewportView(ongoingList);

        jScrollPane4.setViewportView(futureList);

        competedLabel.setText("Completed travels:");

        futureLabel.setText("Future Travels:");

        ongoingLabel.setText("Today's travels:");

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        closeManageBookingButton.setText("Close Page");
        closeManageBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeManageBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageBookingFrameLayout = new javax.swing.GroupLayout(manageBookingFrame.getContentPane());
        manageBookingFrame.getContentPane().setLayout(manageBookingFrameLayout);
        manageBookingFrameLayout.setHorizontalGroup(
            manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageBookingFrameLayout.createSequentialGroup()
                .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageBookingFrameLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(competedLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ongoingLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageBookingFrameLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(closeManageBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(futureLabel)))
                    .addGroup(manageBookingFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        manageBookingFrameLayout.setVerticalGroup(
            manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageBookingFrameLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(manageBookingFrameLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(competedLabel)
                            .addComponent(ongoingLabel)
                            .addComponent(futureLabel))
                        .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageBookingFrameLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageBookingFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(manageBookingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(manageBookingFrameLayout.createSequentialGroup()
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(closeManageBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        editNcustomiseFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                editNcustomiseFrameWindowActivated(evt);
            }
        });

        editLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        editLabel.setText("Edit and customise travel");

        editInfoLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        editInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editInfoLabel.setText("Flight Information");

        se01Box.setText("Snack pack");
        se01Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                se01BoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Available in-flight services:");

        se02Box.setText("Sleeping gears");
        se02Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                se02BoxActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(boughtServicesList);

        jLabel3.setText("You have purchased: ");

        buyServiceButton.setText("Purchase");
        buyServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyServiceButtonActionPerformed(evt);
            }
        });

        changeSeatButton.setText("Change Seat");
        changeSeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSeatButtonActionPerformed(evt);
            }
        });

        closePageButton.setText("Close Page");
        closePageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closePageButtonActionPerformed(evt);
            }
        });

        cancelBookingButton.setText("Cancel Booking");
        cancelBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingButtonActionPerformed(evt);
            }
        });

        removeServiceButton.setText("Remove");
        removeServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeServiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editNcustomiseFrameLayout = new javax.swing.GroupLayout(editNcustomiseFrame.getContentPane());
        editNcustomiseFrame.getContentPane().setLayout(editNcustomiseFrameLayout);
        editNcustomiseFrameLayout.setHorizontalGroup(
            editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editNcustomiseFrameLayout.createSequentialGroup()
                .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editNcustomiseFrameLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(editLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editNcustomiseFrameLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editNcustomiseFrameLayout.createSequentialGroup()
                                .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(se01Box)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editNcustomiseFrameLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(closePageButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(changeSeatButton)
                                .addGap(115, 115, 115)
                                .addComponent(cancelBookingButton))
                            .addGroup(editNcustomiseFrameLayout.createSequentialGroup()
                                .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(buyServiceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(se02Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        editNcustomiseFrameLayout.setVerticalGroup(
            editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editNcustomiseFrameLayout.createSequentialGroup()
                .addComponent(editLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(editInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editNcustomiseFrameLayout.createSequentialGroup()
                        .addComponent(se01Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(se02Box))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyServiceButton)
                    .addComponent(removeServiceButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(editNcustomiseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBookingButton)
                    .addComponent(changeSeatButton)
                    .addComponent(closePageButton))
                .addGap(45, 45, 45))
        );

        changeSeatLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        changeSeatLabel.setText("Please chooose your seat: ");

        changeSeatRowLabel.setText("Row:");

        changeSeatNumberLabel.setText("Number:");

        changeSeatRowBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "D", "F" }));

        changeSeatNumberBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        changeSeatConfirmButton.setText("Confirm");
        changeSeatConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSeatConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeSeatDialogLayout = new javax.swing.GroupLayout(changeSeatDialog.getContentPane());
        changeSeatDialog.getContentPane().setLayout(changeSeatDialogLayout);
        changeSeatDialogLayout.setHorizontalGroup(
            changeSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeSeatDialogLayout.createSequentialGroup()
                .addGroup(changeSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeSeatDialogLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(changeSeatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changeSeatDialogLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(changeSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeSeatRowLabel)
                            .addComponent(changeSeatRowBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(changeSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeSeatNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeSeatNumberLabel))))
                .addGap(103, 103, 103))
            .addGroup(changeSeatDialogLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(changeSeatConfirmButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changeSeatDialogLayout.setVerticalGroup(
            changeSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeSeatDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(changeSeatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(changeSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeSeatRowLabel)
                    .addComponent(changeSeatNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changeSeatDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeSeatRowBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSeatNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(changeSeatConfirmButton)
                .addGap(51, 51, 51))
        );

        warningCanceLabel.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        warningCanceLabel.setForeground(new java.awt.Color(236, 19, 19));
        warningCanceLabel.setText("Warning:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Are you sure to cancel this reservation?");

        confirmCancelButton.setText("Yes");
        confirmCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmCancelButtonActionPerformed(evt);
            }
        });

        notCancel.setText("No");
        notCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cancelBookingDialogLayout = new javax.swing.GroupLayout(cancelBookingDialog.getContentPane());
        cancelBookingDialog.getContentPane().setLayout(cancelBookingDialogLayout);
        cancelBookingDialogLayout.setHorizontalGroup(
            cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBookingDialogLayout.createSequentialGroup()
                .addGroup(cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelBookingDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(warningCanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cancelBookingDialogLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cancelBookingDialogLayout.createSequentialGroup()
                                .addComponent(notCancel)
                                .addGap(242, 242, 242)
                                .addComponent(confirmCancelButton))
                            .addComponent(jLabel4))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        cancelBookingDialogLayout.setVerticalGroup(
            cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBookingDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningCanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notCancel)
                    .addComponent(confirmCancelButton))
                .addGap(36, 36, 36))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        mainLabel.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Take off towards your dream!");

        welcomeLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Weclome, !");

        departureBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SYD", "MEL", "CBR" }));
        departureBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureBoxActionPerformed(evt);
            }
        });

        destinationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SYD", "MEL", "CBR" }));
        destinationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationBoxActionPerformed(evt);
            }
        });

        departureLabel.setText("Departure:");

        destinationLabel.setText("Destination:");

        dateLabel.setText("Date:");

        searchFlightButton.setText("Search For a Flight!");
        searchFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightButtonActionPerformed(evt);
            }
        });

        warningLabel.setForeground(new java.awt.Color(243, 12, 12));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setViewportView(foundFlightsList);

        bookFlightButton.setText("Book This Flight!");
        bookFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightButtonActionPerformed(evt);
            }
        });

        manageBookingButton.setText("Manage My Bookings");
        manageBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(948, Short.MAX_VALUE)
                        .addComponent(dateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(564, 564, 564)
                                    .addComponent(destinationLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(destinationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(425, 425, 425)
                                    .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(341, 341, 341)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(546, 546, 546)
                                    .addComponent(bookFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(273, 273, 273)
                                    .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addComponent(departureLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(departureBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(96, 96, 96)
                                    .addComponent(searchFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(manageBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(departureBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(departureLabel)
                        .addComponent(dateLabel)
                        .addComponent(destinationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(destinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(searchFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bookFlightButton)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        welcomeLabel.setText("Welcome, " + username + "!");
        try{
            currentCustomer = new Customer(username);
        }
        catch(Exception e){
            System.out.println("error happenes");
            dispose();
        }
        foundFlightsList.setModel(model);
        bookFlightButton.setVisible(false);
        //read the flights from txt
        BufferedReader br = null;
        try{
           br = new BufferedReader(new FileReader("flight.txt"));
           String line = null;
           while((line = br.readLine()) != null && !line.equals("")){
               String[] splittedLine = line.split(",");
               int flightPrice = Integer.parseInt(splittedLine[4]);
               Flight f = new Flight(splittedLine[0],splittedLine[1],splittedLine[2],splittedLine[3],flightPrice);
               flightInfo.add(f);
           }
        }
        catch(FileNotFoundException e){
            warningLabel.setText("Flight info file not found, please check the file!");
        }
        catch(IOException e){
            warningLabel.setText("Read file error!");
        }
        finally{
            try{
                if(br != null){
                    br.close();
                }
            }
            catch(IOException e){
                warningLabel.setText("read file error!");
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void departureBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureBoxActionPerformed

    private void destinationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationBoxActionPerformed

    private void searchFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightButtonActionPerformed
        //System.out.println("Button clicked");
        searchedFlights.clear();
        model.removeAllElements();
        foundFlightsList.clearSelection();
        bookFlightButton.setVisible(false);
        String departure = departureBox.getSelectedItem().toString();
        String destination = destinationBox.getSelectedItem().toString();
        Date departureDate = dateChooser.getDate();
        Date today = new Date();
        if(departureDate==null){
            warningLabel.setText("Please select a date!");
            return;
        }
        if(departure.equals(destination)){
            warningLabel.setText("Departure and destination can't be the same!");
            return;
        }
        if(departureDate.before(today)){
            warningLabel.setText("Please select a date later than today!");
        }
        String formattedDate = sdf.format(departureDate);
        for(Flight f: flightInfo){
            if(f.getDeparture().equals(departure) && f.getDestination().equals(destination)){
                String completedFlightInfo = f.getFlightNo() + " , From " + f.getFullDeparture() + " To " + f.getFullDestination() + " , " +formattedDate  + " , " + f.getTakeOff() + " , $" +f.getPrice();
                model.addElement(completedFlightInfo);
                searchedFlights.add(f);
            }
        }
        if(searchedFlights.isEmpty()){
            warningLabel.setText("No flights found!");
        }
        else{
            bookFlightButton.setVisible(true);
        }
    }//GEN-LAST:event_searchFlightButtonActionPerformed

    private void bookFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightButtonActionPerformed
        String selectedFlight = foundFlightsList.getSelectedValue();
        //System.out.println(selectedFlight);
        if(selectedFlight == null){
            warningLabel.setText("Please select one flight!");
            return;
        }
        String[] flightDetailedInfo = selectedFlight.split(" , ");
        dialogInformation1.setText("Flight Number: " + flightDetailedInfo[0]);
        dialogInformation2.setText("Trip: " + flightDetailedInfo[1]);
        dialogInformation3.setText("Departure Time: " + flightDetailedInfo[2] + " " + flightDetailedInfo[3]);
        dialogInformation4.setText(flightDetailedInfo[4] + " will be deducted from your credit.");
        confirmBookingDialog.pack();
        confirmBookingDialog.setVisible(true);
        currentCustomer.setTempTrip(flightDetailedInfo[0], flightDetailedInfo[2]);
        model.removeAllElements();
        foundFlightsList.clearSelection();
    }//GEN-LAST:event_bookFlightButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        confirmBookingDialog.dispose();
        currentCustomer.discardTempTrip();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        chooseSeatDialog.pack();
        chooseSeatDialog.setVisible(true);
        confirmBookingDialog.dispose();
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void seatConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatConfirmButtonActionPerformed
        String seatNo = rowBox.getSelectedItem().toString() + numberBox.getSelectedItem().toString();
        System.out.println(seatNo);
        //currentCustomer.discardTempTrip();
        //check if this seat number is occupied;
        boolean seatOccupied = true;
        String filePath = currentCustomer.getTempTrip().getFlightNo() + "/" + currentCustomer.getTempTrip().getDepartureDate()+".txt";
        File dateFile = new File(filePath);
        if(dateFile.exists() && !dateFile.isDirectory()){
            try {
                seatOccupied = false;
                Scanner reader = new Scanner(dateFile);
                while(reader.hasNextLine()){
                    String line = reader.nextLine();
                    if(line.equals("")) continue;
                    String[] splittedLine = line.split(":");
                    if(splittedLine[0].equals(seatNo)){
                        seatOccupied = true;
                        break;
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FDAIndex.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            seatOccupied = false;
            try {
                dateFile.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(FDAIndex.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(seatOccupied){
            
        }
        else{
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter(filePath,true));
                bw.append(seatNo + ":" + username);
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(FDAIndex.class.getName()).log(Level.SEVERE, null, ex);
            }
            currentCustomer.getTempTrip().setSeatNo(seatNo);
            currentCustomer.pushTempTrip();
            bookingSuccess.pack();
            bookingSuccess.setVisible(true);
            chooseSeatDialog.dispose();
        }
        
    }//GEN-LAST:event_seatConfirmButtonActionPerformed

    private void bkSuccessBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkSuccessBackButtonActionPerformed
        bookingSuccess.dispose();
    }//GEN-LAST:event_bkSuccessBackButtonActionPerformed

    private void manageBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBookingButtonActionPerformed
        manageBookingFrame.pack();
        manageBookingFrame.setVisible(true);
        model.clear();
        foundFlightsList.clearSelection();
    }//GEN-LAST:event_manageBookingButtonActionPerformed

    private void manageBookingFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_manageBookingFrameWindowActivated
        DefaultListModel<String> pastModel = new DefaultListModel();
        DefaultListModel<String> todayModel = new DefaultListModel();
        futureModel = new DefaultListModel();
        completedList.setModel(pastModel);
        ongoingList.setModel(todayModel);
        futureList.setModel(futureModel);
        
        ArrayList<Trip> completedTravels = currentCustomer.getPastTrips();
        for(Trip p: completedTravels){
            String s = p.getFlightNo() + " " + p.getDepartureDate();
            System.out.println(s);
            pastModel.addElement(s);
        }
        ArrayList<Trip> ongoingTravels = currentCustomer.getOngoingTrips();
        for(Trip p: ongoingTravels){
            String s = p.getFlightNo() + " " + p.getDepartureDate();
            System.out.println(s);
            todayModel.addElement(s);
        }
        
        ArrayList<Trip> futureTravels = currentCustomer.getFutureTrips();
        for(Trip p: futureTravels){
            String s= p.getFlightNo() + " " + p.getDepartureDate();
            System.out.println(s);
            futureModel.addElement(s);
        }
    }//GEN-LAST:event_manageBookingFrameWindowActivated

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        editingFlight = futureList.getSelectedValue();
        if(editingFlight == null){
            return;
        }
        editNcustomiseFrame.pack();
        editNcustomiseFrame.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void closeManageBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeManageBookingButtonActionPerformed
        manageBookingFrame.dispose();
    }//GEN-LAST:event_closeManageBookingButtonActionPerformed

    private void se01BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_se01BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_se01BoxActionPerformed

    private void se02BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_se02BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_se02BoxActionPerformed

    private void buyServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyServiceButtonActionPerformed
        if(editingTrip == null){
            System.out.println("Please select the trip again!");
            return;
        }
        String flightNo = editingTrip.getFlightNo();
        String departureDate = editingTrip.getDepartureDate();
        ArrayList<String> serviceList = editingTrip.checkServices();
        if(se01Box.isSelected()){
            if(!serviceList.contains("SE01")){
                currentCustomer.addService(flightNo,departureDate,"SE01");
                serviceModel.addElement("Snack pack");
            }
        }
        if(se02Box.isSelected()){
            if(!serviceList.contains("SE02")){
                currentCustomer.addService(flightNo,departureDate,"SE02");
                serviceModel.addElement("Sleeping gears");
            }
        }
        //reset the editingTrip
        editingTrip = currentCustomer.getSingleFutureTrip(flightNo, departureDate);
    }//GEN-LAST:event_buyServiceButtonActionPerformed

    private void removeServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeServiceButtonActionPerformed
        if(editingTrip == null){
            System.out.println("Please select the trip again!");
            return;
        }
        String flightNo = editingTrip.getFlightNo();
        String departureDate = editingTrip.getDepartureDate();
        ArrayList<String> serviceList = editingTrip.checkServices();
        String removingServices = boughtServicesList.getSelectedValue();
        if(removingServices == null){
            return;
        }
        if(removingServices.equals("Snack pack")){
            System.out.println("removing service");
            serviceModel.removeElement("Snack pack");
            if(serviceList.contains("SE01")){
                currentCustomer.removeService(flightNo, departureDate, "SE01");
            }
            editingTrip = currentCustomer.getSingleFutureTrip(flightNo, departureDate);
            return;
        }
        if(removingServices.equals("Sleeping gears")){
            System.out.println("removing service");
            serviceModel.removeElement("Sleeping gears");
            if(serviceList.contains("SE02")){
                currentCustomer.removeService(flightNo, departureDate, "SE02");
            }
            editingTrip = currentCustomer.getSingleFutureTrip(flightNo, departureDate);
            return;
        }
    }//GEN-LAST:event_removeServiceButtonActionPerformed

    private void cancelBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingButtonActionPerformed
        cancelBookingDialog.pack();
        cancelBookingDialog.setVisible(true);
    }//GEN-LAST:event_cancelBookingButtonActionPerformed

    private void editNcustomiseFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editNcustomiseFrameWindowActivated
        //editInfoLabel.setText(editingFlight);
        String[] splittedInfo = editingFlight.split(" ");
        editingTrip = currentCustomer.getSingleFutureTrip(splittedInfo[0], splittedInfo[1]);
        String flightNoAnalyse;
        switch(splittedInfo[0]){
            case "FDA4350":
                flightNoAnalyse = "(From Sydney to Melbourne, departing at 7:25)";
                break;
            case "FDA4351":
                flightNoAnalyse = "(From Melbourne to Sydney, departing at 10:10)";
                break;
            case "FDA4352":
                flightNoAnalyse = "(From Sydney to Melbourne, departing at 15:30)";
                break;
            case "FDA4353":
                flightNoAnalyse = "(From Melbourne to Sydney, departing at 19:45)";
                break;
            case "FDA3429":
                flightNoAnalyse = "(From Sydney to Canberra, departing at 09:30)";
                break;
            case "FDA3428":
                flightNoAnalyse = "(From Canberra to Sydney, departing at 13:15)";
                break;
            case "FDA3427":
                flightNoAnalyse = "(From Sydney to Canberra, departing at 16:25)";
                break;
            case "FDA3426":
                flightNoAnalyse = "(From Canberra to Sydney, departing at 20:08)";
                break;
            case "FDA7324":
                flightNoAnalyse = "(From Canberra to Melbourne, departing at 07:45)";
                break;
            case "FDA7325":
                flightNoAnalyse = "(From Melbourne to Canberra, departing at 11:24)";
                break;
            default:
                flightNoAnalyse = "";
                break;            
        }
        editInfoLabel.setText(editingFlight + " " + flightNoAnalyse);
        boughtServicesList.setModel(serviceModel);
    }//GEN-LAST:event_editNcustomiseFrameWindowActivated

    private void changeSeatConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSeatConfirmButtonActionPerformed
        if(editingTrip == null){
            System.out.println("Please select the trip again!");
            return;
        }
        String newSeatNumber = changeSeatRowBox.getSelectedItem().toString() + changeSeatNumberBox.getSelectedItem().toString();
        if(newSeatNumber.equals(editingTrip.getSeatNo())){
            System.out.println("Keep unchanged");
            changeSeatDialog.dispose();
            return;
        }
        //check the file
        String filePath = editingTrip.getFlightNo() + "/" + editingTrip.getDepartureDate() + ".txt";
        try {
            BufferedReader br = new BufferedReader(new FileReader(filePath));
            String line;
            while((line = br.readLine())!= null){
                if(line.contains(newSeatNumber)){
                    System.out.println("already occupied!");
                    return;
                }
            }
            currentCustomer.changeSeatNo(editingTrip.getFlightNo(), editingTrip.getDepartureDate(), newSeatNumber);
            changeSeatDialog.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FDAIndex.class.getName()).log(Level.SEVERE, null, ex);
            return;
        } catch (IOException ex) {
            Logger.getLogger(FDAIndex.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        
    }//GEN-LAST:event_changeSeatConfirmButtonActionPerformed

    private void changeSeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSeatButtonActionPerformed
        if(editingTrip == null){
            System.out.println("Please select the trip again!");
            return;
        }
        changeSeatDialog.pack();
        changeSeatDialog.setVisible(true);
    }//GEN-LAST:event_changeSeatButtonActionPerformed

    private void confirmCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmCancelButtonActionPerformed
        if(editingTrip == null) return;
        cancelBookingDialog.dispose();
        editNcustomiseFrame.dispose();
        futureModel.removeElement(editingTrip.getFlightNo() + " " + editingTrip.getDepartureDate());
        currentCustomer.cancelFlight(editingTrip.getFlightNo(), editingTrip.getDepartureDate());
        editingTrip = null;
    }//GEN-LAST:event_confirmCancelButtonActionPerformed

    private void notCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notCancelActionPerformed
        cancelBookingDialog.dispose();
    }//GEN-LAST:event_notCancelActionPerformed

    private void closePageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closePageButtonActionPerformed
       editNcustomiseFrame.dispose();
    }//GEN-LAST:event_closePageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDAIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDAIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDAIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDAIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDAIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkSuccessBackButton;
    private static javax.swing.JButton bookFlightButton;
    private static javax.swing.JDialog bookingSuccess;
    private static javax.swing.JList<String> boughtServicesList;
    private javax.swing.JButton buyServiceButton;
    private javax.swing.JButton cancelBookingButton;
    private javax.swing.JDialog cancelBookingDialog;
    private static javax.swing.JButton cancelButton;
    private javax.swing.JButton changeSeatButton;
    private javax.swing.JButton changeSeatConfirmButton;
    private static javax.swing.JDialog changeSeatDialog;
    private javax.swing.JLabel changeSeatLabel;
    private static javax.swing.JComboBox<String> changeSeatNumberBox;
    private javax.swing.JLabel changeSeatNumberLabel;
    private static javax.swing.JComboBox<String> changeSeatRowBox;
    private javax.swing.JLabel changeSeatRowLabel;
    private static javax.swing.JDialog chooseSeatDialog;
    private javax.swing.JLabel chooseSeatLabel;
    private javax.swing.JButton closeManageBookingButton;
    private javax.swing.JButton closePageButton;
    private javax.swing.JLabel competedLabel;
    private static javax.swing.JList<String> completedList;
    private static javax.swing.JDialog confirmBookingDialog;
    private javax.swing.JButton confirmCancelButton;
    private javax.swing.JLabel confirmTitleLabel;
    private static com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel dateLabel;
    private static javax.swing.JComboBox<String> departureBox;
    private javax.swing.JLabel departureLabel;
    private static javax.swing.JComboBox<String> destinationBox;
    private javax.swing.JLabel destinationLabel;
    private static javax.swing.JLabel dialogInformation1;
    private static javax.swing.JLabel dialogInformation2;
    private static javax.swing.JLabel dialogInformation3;
    private static javax.swing.JLabel dialogInformation4;
    private javax.swing.JButton editButton;
    private static javax.swing.JLabel editInfoLabel;
    private javax.swing.JLabel editLabel;
    private javax.swing.JFrame editNcustomiseFrame;
    private static javax.swing.JList<String> foundFlightsList;
    private javax.swing.JLabel futureLabel;
    private static javax.swing.JList<String> futureList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JButton manageBookingButton;
    private javax.swing.JFrame manageBookingFrame;
    private javax.swing.JButton notCancel;
    private static javax.swing.JComboBox<String> numberBox;
    private javax.swing.JLabel ongoingLabel;
    private static javax.swing.JList<String> ongoingList;
    private static javax.swing.JButton proceedButton;
    private javax.swing.JButton removeServiceButton;
    private static javax.swing.JComboBox<String> rowBox;
    private javax.swing.JLabel rowLabel;
    private javax.swing.JLabel rowLabel1;
    private static javax.swing.JCheckBox se01Box;
    private static javax.swing.JCheckBox se02Box;
    private javax.swing.JButton searchFlightButton;
    private javax.swing.JButton seatConfirmButton;
    private javax.swing.JLabel successLabel;
    private javax.swing.JLabel successTextLabel;
    private javax.swing.JLabel warningCanceLabel;
    private static javax.swing.JLabel warningLabel;
    private static javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
