/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cnlightsoul
 */
public class FDALogin extends javax.swing.JFrame {
    static String[] usernames = new String[100];
    static String[] passwords = new String[100];
    static int existingUsers = 0;
    /**
     * Creates new form FDALogin
     */
    public FDALogin() {
        super("FDA Login");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerWindow = new javax.swing.JFrame();
        registerTitleLabel = new javax.swing.JLabel();
        registerUsernameField = new javax.swing.JTextField();
        registerPasswordField = new javax.swing.JPasswordField();
        registerConfirmPasswordField = new javax.swing.JPasswordField();
        usernameReisterLabel = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        confrimLabel = new javax.swing.JLabel();
        registerConfirmButton = new javax.swing.JButton();
        registerWarningLabel = new javax.swing.JLabel();
        titleLable = new javax.swing.JLabel();
        usernameLable = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLable = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        incorrectWarningLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();

        registerTitleLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        registerTitleLabel.setText("Register");

        usernameReisterLabel.setText("Username");

        Password.setText("Password");

        confrimLabel.setText("Confirm Password");

        registerConfirmButton.setText("Create Account");
        registerConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerConfirmButtonActionPerformed(evt);
            }
        });

        registerWarningLabel.setForeground(new java.awt.Color(241, 21, 37));
        registerWarningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout registerWindowLayout = new javax.swing.GroupLayout(registerWindow.getContentPane());
        registerWindow.getContentPane().setLayout(registerWindowLayout);
        registerWindowLayout.setHorizontalGroup(
            registerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerWindowLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(registerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameReisterLabel)
                    .addComponent(Password)
                    .addComponent(confrimLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(registerPasswordField)
                    .addComponent(registerUsernameField)
                    .addComponent(registerConfirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(71, 71, 71))
            .addGroup(registerWindowLayout.createSequentialGroup()
                .addGroup(registerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerWindowLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(registerTitleLabel))
                    .addGroup(registerWindowLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(registerConfirmButton))
                    .addGroup(registerWindowLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(registerWarningLabel)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        registerWindowLayout.setVerticalGroup(
            registerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerWindowLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(registerTitleLabel)
                .addGap(74, 74, 74)
                .addGroup(registerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameReisterLabel))
                .addGap(38, 38, 38)
                .addGroup(registerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password))
                .addGap(38, 38, 38)
                .addGroup(registerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confrimLabel))
                .addGap(28, 28, 28)
                .addComponent(registerConfirmButton)
                .addGap(18, 18, 18)
                .addComponent(registerWarningLabel)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        titleLable.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        titleLable.setText("Welcome to FlyDreamAir!");

        usernameLable.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        usernameLable.setText("Username: ");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordLable.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        passwordLable.setText("Password:");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        incorrectWarningLabel.setForeground(new java.awt.Color(247, 8, 8));
        incorrectWarningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incorrectWarningLabel.setToolTipText("");

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLable)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(incorrectWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(passwordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(passwordField))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(usernameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(registerButton)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton)
                .addGap(18, 18, 18)
                .addComponent(incorrectWarningLabel)
                .addGap(18, 18, 18)
                .addComponent(registerButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String inputtedUserName = usernameField.getText();
        String inputtedPassword = String.valueOf(passwordField.getPassword());
        //green path for test acount inside netbeans
        if(inputtedUserName.equals("test") && inputtedPassword.equals("123456")){
            //incorrectWarningLabel.setText("Login Successful"); 
            dispose();
            FDAIndex index = new FDAIndex(inputtedUserName);
            index.setVisible(true);
            return;
        }
        if(existingUsers == 0){
            incorrectWarningLabel.setText("No users, please register first");
        }
        else{
            boolean userFound = false;
            for(int i = 0; i < existingUsers; i++){
                if(inputtedUserName.equals(usernames[i]) && inputtedPassword.equals(passwords[i])){
                    //incorrectWarningLabel.setText("Login Successful");
                    userFound = true;
                    dispose();
                    FDAIndex index = new FDAIndex(inputtedUserName);
                    index.setVisible(true);
                    break;
                }
            }
            if(!userFound){
                //used for test inside netbeans
                incorrectWarningLabel.setText("Incorrect Uername or Password!");
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        BufferedReader br = null;
        
        try{
           br = new BufferedReader(new FileReader("login.txt"));
           String line = null;
           
           while((line = br.readLine()) != null){
               String[] splittedLine = line.split(",");
               usernames[existingUsers] = splittedLine[0];
               passwords[existingUsers] = splittedLine[1];
               existingUsers++;
               System.out.println("Read user" + existingUsers);
           }
        }
        catch(FileNotFoundException e){
            incorrectWarningLabel.setText("Login credentials file not found, please check the file!");
        }
        catch(IOException e){
            incorrectWarningLabel.setText("Read file error!");
        }
        finally{
            try{
                if(br != null){
                    br.close();
                }
            }
            catch(IOException e){
                incorrectWarningLabel.setText("read file error!");
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        registerWindow.pack();
        registerWindow.setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerConfirmButtonActionPerformed
        String registerUsername = registerUsernameField.getText();
        String registerPassword = String.valueOf(registerPasswordField.getPassword());
        String confirmPassword = String.valueOf(registerConfirmPasswordField.getPassword());
        
        if(registerUsername.equals("") || registerPassword.equals("") || confirmPassword.equals("")){
            registerWarningLabel.setText("Please fill in all fields!");
            return;
        }
        if(registerUsername.contains(",") || registerPassword.contains(",") || confirmPassword.contains(",")){
            registerWarningLabel.setText("Illegal character ',' used!");
            return;
        }
        if(!registerPassword.equals(confirmPassword)){
            registerWarningLabel.setText("Password and Confirm Password are not identical!");
            return;
        }
        
        String fName = registerUsername + ".txt";
        File newUser = new File(fName);
        try {
            if(newUser.createNewFile()){
                BufferedWriter bw = new BufferedWriter(new FileWriter("login.txt",true));
                bw.newLine();
                bw.flush();
                bw.append(registerUsername + "," + registerPassword);
                bw.close();
                incorrectWarningLabel.setText("New user created!");
                registerWindow.dispose();
            }
            else{
                registerWarningLabel.setText("This user already exists!");
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(FDALogin.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }//GEN-LAST:event_registerConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDALogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDALogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDALogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDALogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDALogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    private javax.swing.JLabel confrimLabel;
    private static javax.swing.JLabel incorrectWarningLabel;
    protected javax.swing.JButton loginButton;
    private static javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JButton registerButton;
    private static javax.swing.JButton registerConfirmButton;
    private static javax.swing.JPasswordField registerConfirmPasswordField;
    private static javax.swing.JPasswordField registerPasswordField;
    private javax.swing.JLabel registerTitleLabel;
    private static javax.swing.JTextField registerUsernameField;
    private static javax.swing.JLabel registerWarningLabel;
    private static javax.swing.JFrame registerWindow;
    private javax.swing.JLabel titleLable;
    private static javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLable;
    private javax.swing.JLabel usernameReisterLabel;
    // End of variables declaration//GEN-END:variables
}
